name: CI
on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always
  MACOSX_DEPLOYMENT_TARGET: 10.11

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        id: install_rust
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Install Linux-specific packages
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install clang-format

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: |
            v2-${{ github.workflow }}-${{ runner.os }}-rust-${{ steps.install_rust.outputs.rustc_hash }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            v2-${{ github.workflow }}-${{ runner.os }}-rust-${{ steps.install_rust.outputs.rustc_hash }}-
            v2-${{ github.workflow }}-${{ runner.os }}-rust-

      - name: cargo check
        run: cargo check --verbose --workspace --all-targets

      - name: cargo build
        run: cargo build --verbose

      - name: cargo test
        run: cargo test --verbose --workspace

      - name: cargo fmt
        if: runner.os == 'Linux'
        run: cargo fmt --verbose --all -- --check

      - name: cargo clippy
        if: runner.os == 'Linux'
        run: cargo clippy --verbose --workspace

      - name: Generate FFI headers
        run: scripts/generate-ffi-headers.sh

      - name: Check FFI headers
        if: runner.os == 'Linux'
        run: git diff --color=always --exit-code ffi/crosslocale.h

      - name: Build Node.js bindings
        working-directory: node-bindings
        run: |
          npm install --ignore-scripts
          npm run node-gyp rebuild -- --debug -- -D rust_build_profile=debug

      - name: Test Node.js bindings
        run: |
          set -x
          crosslocale="$PWD/target/debug/crosslocale"
          test_js="$PWD/node-bindings/test.js"
          cd "${RUNNER_TEMP}"
          curl -fSLO http://stronghold.crosscode.ru/~notabridge/crosscode.tgz
          curl -fSLO https://github.com/dmitmel/crosslocale-scans/raw/master/scan-1.4.2-1.json
          tar xzvf crosscode.tgz
          "$crosslocale" create-project ./tmp --translation-locale=ru_RU ./scan-1.4.2-1.json
          "$crosslocale" import ./tmp --format=cc-ru-chapter-fragments ./crosscode/chapter-fragments
          node "$test_js"

      - name: clang-format
        if: runner.os == 'Linux'
        run: clang-format --verbose --dry-run ffi/crosslocale.h node-bindings/addon.cc
